[pytest]
testpaths = src/main/ui/tests src/main/api/tests
pythonpath = .
python_files = test_*.py
addopts = --alluredir=allure-results --clean-alluredir -v

markers =
    api: Api Test
    ui: UI Test

